<?php

namespace App\Enums;

enum ApiCode: string
{
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case USER_REGISTERED = 'USER_REGISTERED';
    case USER_LOGGED_IN = 'USER_LOGGED_IN';
    case USER_RETURNED = 'USER_RETURNED';
    case USER_LOGGED_OUT = 'USER_LOGGED_OUT';
    case USER_LOGOUT_ALL = 'USER_LOGOUT_ALL';
    case USER_UPDATED = 'USER_UPDATED';
    case INGREDIENT_CREATED = 'INGREDIENT_CREATED';
    case INGREDIENT_RETURNED = 'INGREDIENT_RETURNED';
    case INGREDIENT_UPDATED = 'INGREDIENT_UPDATED';
    case INGREDIENT_DELETED = 'INGREDIENT_DELETED';
    case INGREDIENTS_RETURNED = 'INGREDIENTS_RETURNED';
    case RECIPE_CREATED = 'RECIPE_CREATED';
    case RECIPE_RETURNED = 'RECIPE_RETURNED';
    case RECIPES_RETURNED = 'RECIPES_RETURNED';
    case RECIPE_UPDATED = 'RECIPE_UPDATED';
    case RECIPE_DELETED = 'RECIPE_DELETED';
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case ACCESS_DENIED = 'ACCESS_DENIED';
}


